"""initial schema

Revision ID: 1ba46d45cdac
Revises: 
Create Date: 2026-07-21 09:57:29.842591

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ba46d45cdac'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('artifact_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b2_key')
    )
    op.create_index(op.f('ix_artifact_objects_workspace_id'), 'artifact_objects', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('campaign', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('publication_status', sa.String(length=30), nullable=False),
    sa.Column('parent_asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_parent_asset_id'), 'assets', ['parent_asset_id'], unique=False)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_node', sa.String(length=80), nullable=False),
    sa.Column('target_node', sa.String(length=80), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_details', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=80), nullable=False),
    sa.Column('human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_edges_workspace_id'), 'dependency_edges', ['workspace_id'], unique=False)
    op.create_table('source_of_truth_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_of_truth_items_workspace_id'), 'source_of_truth_items', ['workspace_id'], unique=False)
    op.create_table('asset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=False),
    sa.Column('preview_b2_key', sa.String(length=500), nullable=True),
    sa.Column('analysis_b2_key', sa.String(length=500), nullable=True),
    sa.Column('manifest_b2_key', sa.String(length=500), nullable=True),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_versions_asset_id'), 'asset_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_versions_sha256'), 'asset_versions', ['sha256'], unique=False)
    op.create_table('source_of_truth_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_sha256', sa.String(length=64), nullable=True),
    sa.Column('reference_phash', sa.String(length=32), nullable=True),
    sa.Column('b2_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['source_of_truth_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_of_truth_versions_item_id'), 'source_of_truth_versions', ['item_id'], unique=False)
    op.create_table('recall_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=36), nullable=False),
    sa.Column('old_version_id', sa.String(length=36), nullable=False),
    sa.Column('new_version_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('markets', sa.JSON(), nullable=False),
    sa.Column('requested_action', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_version_id'], ['source_of_truth_versions.id'], ),
    sa.ForeignKeyConstraint(['old_version_id'], ['source_of_truth_versions.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_of_truth_items.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recall_events_workspace_id'), 'recall_events', ['workspace_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('edges_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_workspace_id'), 'analysis_runs', ['workspace_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_recall_event_id'), 'audit_events', ['recall_event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('recall_impacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('score_components', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('strongest_path', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recall_impacts_asset_id'), 'recall_impacts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_recall_impacts_recall_event_id'), 'recall_impacts', ['recall_event_id'], unique=False)
    op.create_table('repair_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_plans_asset_id'), 'repair_plans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_repair_plans_idempotency_key'), 'repair_plans', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_repair_plans_recall_event_id'), 'repair_plans', ['recall_event_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('new_classification', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_asset_id'), 'review_decisions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_recall_event_id'), 'review_decisions', ['recall_event_id'], unique=False)
    op.create_table('repair_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_event_id', sa.String(length=36), nullable=False),
    sa.Column('repair_plan_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=40), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('result_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recall_event_id'], ['recall_events.id'], ),
    sa.ForeignKeyConstraint(['repair_plan_id'], ['repair_plans.id'], ),
    sa.ForeignKeyConstraint(['result_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_jobs_asset_id'), 'repair_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_repair_jobs_idempotency_key'), 'repair_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_repair_jobs_recall_event_id'), 'repair_jobs', ['recall_event_id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_job_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('genblaze_pipeline', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('manifest_b2_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_job_id'], ['repair_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_repair_job_id'), 'generation_runs', ['repair_job_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_job_id', sa.String(length=36), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['repair_job_id'], ['repair_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_repair_job_id'), 'validation_results', ['repair_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_repair_job_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_generation_runs_repair_job_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_repair_jobs_recall_event_id'), table_name='repair_jobs')
    op.drop_index(op.f('ix_repair_jobs_idempotency_key'), table_name='repair_jobs')
    op.drop_index(op.f('ix_repair_jobs_asset_id'), table_name='repair_jobs')
    op.drop_table('repair_jobs')
    op.drop_index(op.f('ix_review_decisions_recall_event_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_asset_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_repair_plans_recall_event_id'), table_name='repair_plans')
    op.drop_index(op.f('ix_repair_plans_idempotency_key'), table_name='repair_plans')
    op.drop_index(op.f('ix_repair_plans_asset_id'), table_name='repair_plans')
    op.drop_table('repair_plans')
    op.drop_index(op.f('ix_recall_impacts_recall_event_id'), table_name='recall_impacts')
    op.drop_index(op.f('ix_recall_impacts_asset_id'), table_name='recall_impacts')
    op.drop_table('recall_impacts')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_recall_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_analysis_runs_workspace_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_recall_events_workspace_id'), table_name='recall_events')
    op.drop_table('recall_events')
    op.drop_index(op.f('ix_source_of_truth_versions_item_id'), table_name='source_of_truth_versions')
    op.drop_table('source_of_truth_versions')
    op.drop_index(op.f('ix_asset_versions_sha256'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_asset_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_index(op.f('ix_source_of_truth_items_workspace_id'), table_name='source_of_truth_items')
    op.drop_table('source_of_truth_items')
    op.drop_index(op.f('ix_dependency_edges_workspace_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_parent_asset_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_artifact_objects_workspace_id'), table_name='artifact_objects')
    op.drop_table('artifact_objects')
    op.drop_table('workspaces')
    op.drop_table('provider_configurations')
    # ### end Alembic commands ###
